drop table IF EXISTS contacts;
drop table IF EXISTS contact_items;

create table contacts (
    id BIGINT generated by default as identity PRIMARY KEY,
    fullName VARCHAR(250) NOT NULL,
    job VARCHAR(100)
);

create table contact_items (
    id BIGINT generated by default as identity PRIMARY KEY,
    contact_id BIGINT NOT NULL,
    contact_item_type VARCHAR(50) NOT NULL,
    value VARCHAR(250) DEFAULT NULL
);

alter table contact_items add constraint FK_contact foreign key (contact_id) references contacts(id);